blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/security/advisories/new
    about: Report security issues privately through GitHub Security Advisories
  - name: GitHub Discussions - Q&A
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: GitHub Discussions - Ideas
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/discussions/categories/ideas
    about: Share ideas and discuss potential features before opening a formal feature request
  - name: Documentation
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/README.md
    about: Read the documentation (README.md, ARCHITECTURE.md, BETA_TESTING.md)
